version: '3'
services:
  postgres:
    image: postgres:11
    container_name: postgres
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: docker_db
    ports:
      - "5432:5432"
    restart: always

  app:
    build: src/
    ports:
      - "8080:8080"
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
    restart: always
    links:
      - postgres